# Step 1: Build stage
FROM node:20-alpine AS builder
WORKDIR /app

# Dependencies install
COPY package*.json ./
RUN npm ci

# Code copy karke build
COPY . .
RUN npm run build

# Step 2: Run stage - choti image ke liye
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Sirf zaroori files copy karo
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3000
CMD ["node", "server.js"]