name: Mybuild
on: 
  push:
    branches: [ main ]
  workflow_dispatch: # manual run ka button bhi

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node Latest
        uses: actions/setup-node@v4
        with: 
          node-version: '24'  # ya '24' bhi laga sakte ho
          cache: 'npm' # npm ci fast ho jayega

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint
        continue-on-error: true

      - name: Build NextJS
        run: npm run build
