name: Mybuild
on: 
  push:
    branches: [ main ] # 1. Ye add kar do warna har branch par chalega

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: {node-version: '24'} # 2. Node 23 mat lo. NextJS ke liye 20 LTS best hai
      - run: npm ci
      - run: npm run lint
        continue-on-error: true # Lint fail ho to bhi build chale
      - run: npm run build
