name: CI - Test and Lint

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:  # PR banate hi chalega

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Code download karo
        uses: actions/checkout@v4
      - name: Hello bolo
        run: echo "Assalamualaikum! Main ${{ github.actor }} hun"
   